# -*- encoding: utf-8 -*-
##############################################################
##  Author: Abdulmumen Naas
##	Description: Arabic Natural Language Processor (Kalam-lp)
##	Version: 0.0.1
##  Copyright (c) 2014 Abdulmumen Naas
#############################################################

import re
import string
#import unicodeTable

##                                                
# Arabic Unicode Characters Glabals
##
ARABIC_NUMBER_SIGN = u"\u0600"
ARABIC_SIGN_SANAH = u"\u0601"
ARABIC_FOOTNOTE_MARKER = u"\u0602"
ARABIC_SIGN_SAFHA = u"\u0603"
ARABIC_SIGN_SAMVAT = u"\u0604"
 #= u"\u0605"
ARABIC_INDIC_CUBE_ROOT = u"\u0606"
ARABIC_INDIC_FOURTH_ROOT = u"\u0607"
ARABIC_RAY = u"\u0608"
ARABIC_INDIC_PER_MILLE_SIGN = u"\u0609"
ARABIC_INDIC_PER_TEN_THOUSAND_SIGN = u"\u060a"
AFGHANI_SIGN = u"\u060b"
ARABIC_COMMA = u"\u060c"
ARABIC_DATE_SEPARATOR = u"\u060d"
ARABIC_POETIC_VERSE_SIGN = u"\u060e"
ARABIC_SIGN_MISRA = u"\u060f"
ARABIC_SIGN_SALLALLAHOU_ALAYHE_WASSALLAM = u"\u0610"
ARABIC_SIGN_ALAYHE_ASSALLAM = u"\u0611"
ARABIC_SIGN_RAHMATULLAH_ALAYHE = u"\u0612"
ARABIC_SIGN_RADI_ALLAHOU_ANHU = u"\u0613"
ARABIC_SIGN_TAKHALLUS = u"\u0614"
ARABIC_SMALL_HIGH_TAH = u"\u0615"
ARABIC_SMALL_HIGH_LIGATURE_ALEF_WITH_LAM_WITH_YEH = u"\u0616"
ARABIC_SMALL_HIGH_ZAIN = u"\u0617"
ARABIC_SMALL_FATHA = u"\u0618"
ARABIC_SMALL_DAMMA = u"\u0619"
ARABIC_SMALL_KASRA = u"\u061a"
ARABIC_SEMICOLON = u"\u061b"
ARABIC_LETTER_MARK = u"\u061c"
 #= u"\u061d"
ARABIC_TRIPLE_DOT_PUNCTUATION_MARK = u"\u061e"
ARABIC_QUESTION_MARK = u"\u061f"
ARABIC_LETTER_KASHMIRI_YEH = u"\u0620"
ARABIC_LETTER_HAMZA = u"\u0621"
ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE = u"\u0622"
ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE = u"\u0623"
ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE = u"\u0624"
ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW = u"\u0625"
ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE = u"\u0626"
ARABIC_LETTER_ALEF = u"\u0627"
ARABIC_LETTER_BEH = u"\u0628"
ARABIC_LETTER_TEH_MARBUTA = u"\u0629"
#ARABIC_LETTER_TEH = u"\u062a"
ARABIC_LETTER_TEH = u"ت"
ARABIC_LETTER_THEH = u"\u062b"
ARABIC_LETTER_JEEM = u"\u062c"
ARABIC_LETTER_HAH = u"\u062d"
ARABIC_LETTER_KHAH = u"\u062e"
ARABIC_LETTER_DAL = u"\u062f"
ARABIC_LETTER_THAL = u"\u0630"
ARABIC_LETTER_REH = u"\u0631"
ARABIC_LETTER_ZAIN = u"\u0632"
ARABIC_LETTER_SEEN = u"\u0633"
ARABIC_LETTER_SHEEN = u"\u0634"
ARABIC_LETTER_SAD = u"\u0635"
ARABIC_LETTER_DAD = u"\u0636"
ARABIC_LETTER_TAH = u"\u0637"
ARABIC_LETTER_ZAH = u"\u0638"
ARABIC_LETTER_AIN = u"\u0639"
ARABIC_LETTER_GHAIN = u"\u063a"
ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE = u"\u063b"
ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW = u"\u063c"
ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V = u"\u063d"
ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE = u"\u063e"
ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE = u"\u063f"
ARABIC_TATWEEL = u"\u0640"
ARABIC_LETTER_FEH = u"\u0641"
ARABIC_LETTER_QAF = u"\u0642"
ARABIC_LETTER_KAF = u"\u0643"
ARABIC_LETTER_LAM = u"\u0644"
ARABIC_LETTER_MEEM = u"\u0645"
ARABIC_LETTER_NOON = u"\u0646"
ARABIC_LETTER_HEH = u"\u0647"
ARABIC_LETTER_WAW = u"\u0648"
ARABIC_LETTER_ALEF_MAKSURA = u"\u0649"
ARABIC_LETTER_YEH = u"\u064a"
ARABIC_FATHATAN = u"\u064b"
ARABIC_DAMMATAN = u"\u064c"
ARABIC_KASRATAN = u"\u064d"
ARABIC_FATHA = u"\u064e"
ARABIC_DAMMA = u"\u064f"
ARABIC_KASRA = u"\u0650"
ARABIC_SHADDA = u"\u0651"
ARABIC_SUKUN = u"\u0652"
ARABIC_MADDAH_ABOVE = u"\u0653"
ARABIC_HAMZA_ABOVE = u"\u0654"
ARABIC_HAMZA_BELOW = u"\u0655"
ARABIC_SUBSCRIPT_ALEF = u"\u0656"
ARABIC_INVERTED_DAMMA = u"\u0657"
ARABIC_MARK_NOON_GHUNNA = u"\u0658"
ARABIC_ZWARAKAY = u"\u0659"
ARABIC_VOWEL_SIGN_SMALL_V_ABOVE = u"\u065a"
ARABIC_VOWEL_SIGN_INVERTED_SMALL_V_ABOVE = u"\u065b"
ARABIC_VOWEL_SIGN_DOT_BELOW = u"\u065c"
ARABIC_REVERSED_DAMMA = u"\u065d"
ARABIC_FATHA_WITH_TWO_DOTS = u"\u065e"
ARABIC_WAVY_HAMZA_BELOW = u"\u065f"
ARABIC_INDIC_DIGIT_ZERO = u"\u0660"
ARABIC_INDIC_DIGIT_ONE = u"\u0661"
ARABIC_INDIC_DIGIT_TWO = u"\u0662"
ARABIC_INDIC_DIGIT_THREE = u"\u0663"
ARABIC_INDIC_DIGIT_FOUR = u"\u0664"
ARABIC_INDIC_DIGIT_FIVE = u"\u0665"
ARABIC_INDIC_DIGIT_SIX = u"\u0666"
ARABIC_INDIC_DIGIT_SEVEN = u"\u0667"
ARABIC_INDIC_DIGIT_EIGHT = u"\u0668"
ARABIC_INDIC_DIGIT_NINE = u"\u0669"
ARABIC_PERCENT_SIGN = u"\u066a"
ARABIC_DECIMAL_SEPARATOR = u"\u066b"
ARABIC_THOUSANDS_SEPARATOR = u"\u066c"
ARABIC_FIVE_POINTED_STAR = u"\u066d"
ARABIC_LETTER_DOTLESS_BEH = u"\u066e"
ARABIC_LETTER_DOTLESS_QAF = u"\u066f"
ARABIC_LETTER_SUPERSCRIPT_ALEF = u"\u0670"
ARABIC_LETTER_ALEF_WASLA = u"\u0671"
ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE = u"\u0672"
ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW = u"\u0673"
ARABIC_LETTER_HIGH_HAMZA = u"\u0674"
ARABIC_LETTER_HIGH_HAMZA_ALEF = u"\u0675"
ARABIC_LETTER_HIGH_HAMZA_WAW = u"\u0676"
ARABIC_LETTER_U_WITH_HAMZA_ABOVE = u"\u0677"
ARABIC_LETTER_HIGH_HAMZA_YEH = u"\u0678"
ARABIC_LETTER_TTEH = u"\u0679"
ARABIC_LETTER_TTEHEH = u"\u067a"
ARABIC_LETTER_BEEH = u"\u067b"
ARABIC_LETTER_TEH_WITH_RING = u"\u067c"
ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS = u"\u067d"
ARABIC_LETTER_PEH = u"\u067e"
ARABIC_LETTER_TEHEH = u"\u067f"
ARABIC_LETTER_BEHEH = u"\u0680"
ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE = u"\u0681"
ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE = u"\u0682"
ARABIC_LETTER_NYEH = u"\u0683"
ARABIC_LETTER_DYEH = u"\u0684"
ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE = u"\u0685"
ARABIC_LETTER_TCHEH = u"\u0686"
ARABIC_LETTER_TCHEHEH = u"\u0687"
ARABIC_LETTER_DDAL = u"\u0688"
ARABIC_LETTER_DAL_WITH_RING = u"\u0689"
ARABIC_LETTER_DAL_WITH_DOT_BELOW = u"\u068a"
ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH = u"\u068b"
ARABIC_LETTER_DAHAL = u"\u068c"
ARABIC_LETTER_DDAHAL = u"\u068d"
ARABIC_LETTER_DUL = u"\u068e"
ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS = u"\u068f"
ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE = u"\u0690"
ARABIC_LETTER_RREH = u"\u0691"
ARABIC_LETTER_REH_WITH_SMALL_V = u"\u0692"
ARABIC_LETTER_REH_WITH_RING = u"\u0693"
ARABIC_LETTER_REH_WITH_DOT_BELOW = u"\u0694"
ARABIC_LETTER_REH_WITH_SMALL_V_BELOW = u"\u0695"
ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE = u"\u0696"
ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE = u"\u0697"
ARABIC_LETTER_JEH = u"\u0698"
ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE = u"\u0699"
ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE = u"\u069a"
ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW = u"\u069b"
ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE = u"\u069c"
ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW = u"\u069d"
ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE = u"\u069e"
ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE = u"\u069f"
ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE = u"\u06a0"
ARABIC_LETTER_DOTLESS_FEH = u"\u06a1"
ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW = u"\u06a2"
ARABIC_LETTER_FEH_WITH_DOT_BELOW = u"\u06a3"
ARABIC_LETTER_VEH = u"\u06a4"
ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW = u"\u06a5"
ARABIC_LETTER_PEHEH = u"\u06a6"
ARABIC_LETTER_QAF_WITH_DOT_ABOVE = u"\u06a7"
ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE = u"\u06a8"
ARABIC_LETTER_KEHEH = u"\u06a9"
ARABIC_LETTER_SWASH_KAF = u"\u06aa"
ARABIC_LETTER_KAF_WITH_RING = u"\u06ab"
ARABIC_LETTER_KAF_WITH_DOT_ABOVE = u"\u06ac"
ARABIC_LETTER_NG = u"\u06ad"
ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW = u"\u06ae"
ARABIC_LETTER_GAF = u"\u06af"
ARABIC_LETTER_GAF_WITH_RING = u"\u06b0"
ARABIC_LETTER_NGOEH = u"\u06b1"
ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW = u"\u06b2"
ARABIC_LETTER_GUEH = u"\u06b3"
ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE = u"\u06b4"
ARABIC_LETTER_LAM_WITH_SMALL_V = u"\u06b5"
ARABIC_LETTER_LAM_WITH_DOT_ABOVE = u"\u06b6"
ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE = u"\u06b7"
ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW = u"\u06b8"
ARABIC_LETTER_NOON_WITH_DOT_BELOW = u"\u06b9"
ARABIC_LETTER_NOON_GHUNNA = u"\u06ba"
ARABIC_LETTER_RNOON = u"\u06bb"
ARABIC_LETTER_NOON_WITH_RING = u"\u06bc"
ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE = u"\u06bd"
ARABIC_LETTER_HEH_DOACHASHMEE = u"\u06be"
ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE = u"\u06bf"
ARABIC_LETTER_HEH_WITH_YEH_ABOVE = u"\u06c0"
ARABIC_LETTER_HEH_GOAL = u"\u06c1"
ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE = u"\u06c2"
ARABIC_LETTER_TEH_MARBUTA_GOAL = u"\u06c3"
ARABIC_LETTER_WAW_WITH_RING = u"\u06c4"
ARABIC_LETTER_KIRGHIZ_OE = u"\u06c5"
ARABIC_LETTER_OE = u"\u06c6"
ARABIC_LETTER_U = u"\u06c7"
ARABIC_LETTER_YU = u"\u06c8"
ARABIC_LETTER_KIRGHIZ_YU = u"\u06c9"
ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE = u"\u06ca"
ARABIC_LETTER_VE = u"\u06cb"
ARABIC_LETTER_FARSI_YEH = u"\u06cc"
ARABIC_LETTER_YEH_WITH_TAIL = u"\u06cd"
ARABIC_LETTER_YEH_WITH_SMALL_V = u"\u06ce"
ARABIC_LETTER_WAW_WITH_DOT_ABOVE = u"\u06cf"
ARABIC_LETTER_E = u"\u06d0"
ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW = u"\u06d1"
ARABIC_LETTER_YEH_BARREE = u"\u06d2"
ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE = u"\u06d3"
ARABIC_FULL_STOP = u"\u06d4"
ARABIC_LETTER_AE = u"\u06d5"
ARABIC_SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA = u"\u06d6"
ARABIC_SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA = u"\u06d7"
ARABIC_SMALL_HIGH_MEEM_INITIAL_FORM = u"\u06d8"
ARABIC_SMALL_HIGH_LAM_ALEF = u"\u06d9"
ARABIC_SMALL_HIGH_JEEM = u"\u06da"
ARABIC_SMALL_HIGH_THREE_DOTS = u"\u06db"
ARABIC_SMALL_HIGH_SEEN = u"\u06dc"
ARABIC_END_OF_AYAH = u"\u06dd"
ARABIC_START_OF_RUB_EL_HIZB = u"\u06de"
ARABIC_SMALL_HIGH_ROUNDED_ZERO = u"\u06df"
ARABIC_SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO = u"\u06e0"
ARABIC_SMALL_HIGH_DOTLESS_HEAD_OF_KHAH = u"\u06e1"
ARABIC_SMALL_HIGH_MEEM_ISOLATED_FORM = u"\u06e2"
ARABIC_SMALL_LOW_SEEN = u"\u06e3"
ARABIC_SMALL_HIGH_MADDA = u"\u06e4"
ARABIC_SMALL_WAW = u"\u06e5"
ARABIC_SMALL_YEH = u"\u06e6"
ARABIC_SMALL_HIGH_YEH = u"\u06e7"
ARABIC_SMALL_HIGH_NOON = u"\u06e8"
ARABIC_PLACE_OF_SAJDAH = u"\u06e9"
ARABIC_EMPTY_CENTRE_LOW_STOP = u"\u06ea"
ARABIC_EMPTY_CENTRE_HIGH_STOP = u"\u06eb"
ARABIC_ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE = u"\u06ec"
ARABIC_SMALL_LOW_MEEM = u"\u06ed"
ARABIC_LETTER_DAL_WITH_INVERTED_V = u"\u06ee"
ARABIC_LETTER_REH_WITH_INVERTED_V = u"\u06ef"
EXTENDED_ARABIC_INDIC_DIGIT_ZERO = u"\u06f0"
EXTENDED_ARABIC_INDIC_DIGIT_ONE = u"\u06f1"
EXTENDED_ARABIC_INDIC_DIGIT_TWO = u"\u06f2"
EXTENDED_ARABIC_INDIC_DIGIT_THREE = u"\u06f3"
EXTENDED_ARABIC_INDIC_DIGIT_FOUR = u"\u06f4"
EXTENDED_ARABIC_INDIC_DIGIT_FIVE = u"\u06f5"
EXTENDED_ARABIC_INDIC_DIGIT_SIX = u"\u06f6"
EXTENDED_ARABIC_INDIC_DIGIT_SEVEN = u"\u06f7"
EXTENDED_ARABIC_INDIC_DIGIT_EIGHT = u"\u06f8"
EXTENDED_ARABIC_INDIC_DIGIT_NINE = u"\u06f9"
ARABIC_LETTER_SHEEN_WITH_DOT_BELOW = u"\u06fa"
ARABIC_LETTER_DAD_WITH_DOT_BELOW = u"\u06fb"
ARABIC_LETTER_GHAIN_WITH_DOT_BELOW = u"\u06fc"
ARABIC_SIGN_SINDHI_AMPERSAND = u"\u06fd"
ARABIC_SIGN_SINDHI_POSTPOSITION_MEN = u"\u06fe"
ARABIC_LETTER_HEH_WITH_INVERTED_V = u"\u06ff"
ARABIC_EXCLAMATION_MARK = u"!"
               
##
#Arabic Letters (Name,Unicode)
##

ARABIC_LETTER_REPR = (("ARABIC NUMBER SIGN",ARABIC_NUMBER_SIGN),
("ARABIC SIGN SANAH",ARABIC_SIGN_SANAH),
("ARABIC FOOTNOTE MARKER",ARABIC_FOOTNOTE_MARKER),
("ARABIC SIGN SAFHA",ARABIC_SIGN_SAFHA),
("ARABIC SIGN SAMVAT",ARABIC_SIGN_SAMVAT),
("ARABIC-INDIC CUBE ROOT",ARABIC_INDIC_CUBE_ROOT),
("ARABIC-INDIC FOURTH ROOT",ARABIC_INDIC_FOURTH_ROOT),
("ARABIC RAY",ARABIC_RAY),
("ARABIC-INDIC PER MILLE SIGN",ARABIC_INDIC_PER_MILLE_SIGN),
("ARABIC-INDIC PER TEN THOUSAND SIGN",ARABIC_INDIC_PER_TEN_THOUSAND_SIGN),
("AFGHANI SIGN",AFGHANI_SIGN),
("ARABIC COMMA",ARABIC_COMMA),
("ARABIC DATE SEPARATOR",ARABIC_DATE_SEPARATOR),
("ARABIC POETIC VERSE SIGN",ARABIC_POETIC_VERSE_SIGN),
("ARABIC SIGN MISRA",ARABIC_SIGN_MISRA),
("ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM",ARABIC_SIGN_SALLALLAHOU_ALAYHE_WASSALLAM),
("ARABIC SIGN ALAYHE ASSALLAM",ARABIC_SIGN_ALAYHE_ASSALLAM),
("ARABIC SIGN RAHMATULLAH ALAYHE",ARABIC_SIGN_RAHMATULLAH_ALAYHE),
("ARABIC SIGN RADI ALLAHOU ANHU",ARABIC_SIGN_RADI_ALLAHOU_ANHU),
("ARABIC SIGN TAKHALLUS",ARABIC_SIGN_TAKHALLUS),
("ARABIC SMALL HIGH TAH",ARABIC_SMALL_HIGH_TAH),
("ARABIC SMALL HIGH LIGATURE ALEF WITH LAM WITH YEH",ARABIC_SMALL_HIGH_LIGATURE_ALEF_WITH_LAM_WITH_YEH),
("ARABIC SMALL HIGH ZAIN",ARABIC_SMALL_HIGH_ZAIN),
("ARABIC SMALL FATHA",ARABIC_SMALL_FATHA),
("ARABIC SMALL DAMMA",ARABIC_SMALL_DAMMA),
("ARABIC SMALL KASRA",ARABIC_SMALL_KASRA),
("ARABIC SEMICOLON",ARABIC_SEMICOLON),
("ARABIC LETTER MARK",ARABIC_LETTER_MARK),
("ARABIC TRIPLE DOT PUNCTUATION MARK",ARABIC_TRIPLE_DOT_PUNCTUATION_MARK),
("ARABIC QUESTION MARK",ARABIC_QUESTION_MARK),
("ARABIC LETTER KASHMIRI YEH",ARABIC_LETTER_KASHMIRI_YEH),
("ARABIC LETTER HAMZA",ARABIC_LETTER_HAMZA),
("ARABIC LETTER ALEF WITH MADDA ABOVE",ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE),
("ARABIC LETTER ALEF WITH HAMZA ABOVE",ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE),
("ARABIC LETTER WAW WITH HAMZA ABOVE",ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE),
("ARABIC LETTER ALEF WITH HAMZA BELOW",ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW),
("ARABIC LETTER YEH WITH HAMZA ABOVE",ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE),
("ARABIC LETTER ALEF",ARABIC_LETTER_ALEF),
("ARABIC LETTER BEH",ARABIC_LETTER_BEH),
("ARABIC LETTER TEH MARBUTA",ARABIC_LETTER_TEH_MARBUTA),
("ARABIC LETTER TEH",ARABIC_LETTER_TEH),
("ARABIC LETTER THEH",ARABIC_LETTER_THEH),
("ARABIC LETTER JEEM",ARABIC_LETTER_JEEM),
("ARABIC LETTER HAH",ARABIC_LETTER_HAH),
("ARABIC LETTER KHAH",ARABIC_LETTER_KHAH),
("ARABIC LETTER DAL",ARABIC_LETTER_DAL),
("ARABIC LETTER THAL",ARABIC_LETTER_THAL),
("ARABIC LETTER REH",ARABIC_LETTER_REH),
("ARABIC LETTER ZAIN",ARABIC_LETTER_ZAIN),
("ARABIC LETTER SEEN",ARABIC_LETTER_SEEN),
("ARABIC LETTER SHEEN",ARABIC_LETTER_SHEEN),
("ARABIC LETTER SAD",ARABIC_LETTER_SAD),
("ARABIC LETTER DAD",ARABIC_LETTER_DAD),
("ARABIC LETTER TAH",ARABIC_LETTER_TAH),
("ARABIC LETTER ZAH",ARABIC_LETTER_ZAH),
("ARABIC LETTER AIN",ARABIC_LETTER_AIN),
("ARABIC LETTER GHAIN",ARABIC_LETTER_GHAIN),
("ARABIC LETTER KEHEH WITH TWO DOTS ABOVE",ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE),
("ARABIC LETTER KEHEH WITH THREE DOTS BELOW",ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER FARSI YEH WITH INVERTED V",ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V),
("ARABIC LETTER FARSI YEH WITH TWO DOTS ABOVE",ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE),
("ARABIC LETTER FARSI YEH WITH THREE DOTS ABOVE",ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE),
("ARABIC TATWEEL",ARABIC_TATWEEL),
("ARABIC LETTER FEH",ARABIC_LETTER_FEH),
("ARABIC LETTER QAF",ARABIC_LETTER_QAF),
("ARABIC LETTER KAF",ARABIC_LETTER_KAF),
("ARABIC LETTER LAM",ARABIC_LETTER_LAM),
("ARABIC LETTER MEEM",ARABIC_LETTER_MEEM),
("ARABIC LETTER NOON",ARABIC_LETTER_NOON),
("ARABIC LETTER HEH",ARABIC_LETTER_HEH),
("ARABIC LETTER WAW",ARABIC_LETTER_WAW),
("ARABIC LETTER ALEF MAKSURA",ARABIC_LETTER_ALEF_MAKSURA),
("ARABIC LETTER YEH",ARABIC_LETTER_YEH),
("ARABIC FATHATAN",ARABIC_FATHATAN),
("ARABIC DAMMATAN",ARABIC_DAMMATAN),
("ARABIC KASRATAN",ARABIC_KASRATAN),
("ARABIC FATHA",ARABIC_FATHA),
("ARABIC DAMMA",ARABIC_DAMMA),
("ARABIC KASRA",ARABIC_KASRA),
("ARABIC SHADDA",ARABIC_SHADDA),
("ARABIC SUKUN",ARABIC_SUKUN),
("ARABIC MADDAH ABOVE",ARABIC_MADDAH_ABOVE),
("ARABIC HAMZA ABOVE",ARABIC_HAMZA_ABOVE),
("ARABIC HAMZA BELOW",ARABIC_HAMZA_BELOW),
("ARABIC SUBSCRIPT ALEF",ARABIC_SUBSCRIPT_ALEF),
("ARABIC INVERTED DAMMA",ARABIC_INVERTED_DAMMA),
("ARABIC MARK NOON GHUNNA",ARABIC_MARK_NOON_GHUNNA),
("ARABIC ZWARAKAY",ARABIC_ZWARAKAY),
("ARABIC VOWEL SIGN SMALL V ABOVE",ARABIC_VOWEL_SIGN_SMALL_V_ABOVE),
("ARABIC VOWEL SIGN INVERTED SMALL V ABOVE",ARABIC_VOWEL_SIGN_INVERTED_SMALL_V_ABOVE),
("ARABIC VOWEL SIGN DOT BELOW",ARABIC_VOWEL_SIGN_DOT_BELOW),
("ARABIC REVERSED DAMMA",ARABIC_REVERSED_DAMMA),
("ARABIC FATHA WITH TWO DOTS",ARABIC_FATHA_WITH_TWO_DOTS),
("ARABIC WAVY HAMZA BELOW",ARABIC_WAVY_HAMZA_BELOW),
("ARABIC-INDIC DIGIT ZERO",ARABIC_INDIC_DIGIT_ZERO),
("ARABIC-INDIC DIGIT ONE",ARABIC_INDIC_DIGIT_ONE),
("ARABIC-INDIC DIGIT TWO",ARABIC_INDIC_DIGIT_TWO),
("ARABIC-INDIC DIGIT THREE",ARABIC_INDIC_DIGIT_THREE),
("ARABIC-INDIC DIGIT FOUR",ARABIC_INDIC_DIGIT_FOUR),
("ARABIC-INDIC DIGIT FIVE",ARABIC_INDIC_DIGIT_FIVE),
("ARABIC-INDIC DIGIT SIX",ARABIC_INDIC_DIGIT_SIX),
("ARABIC-INDIC DIGIT SEVEN",ARABIC_INDIC_DIGIT_SEVEN),
("ARABIC-INDIC DIGIT EIGHT",ARABIC_INDIC_DIGIT_EIGHT),
("ARABIC-INDIC DIGIT NINE",ARABIC_INDIC_DIGIT_NINE),
("ARABIC PERCENT SIGN",ARABIC_PERCENT_SIGN),
("ARABIC DECIMAL SEPARATOR",ARABIC_DECIMAL_SEPARATOR),
("ARABIC THOUSANDS SEPARATOR",ARABIC_THOUSANDS_SEPARATOR),
("ARABIC FIVE POINTED STAR",ARABIC_FIVE_POINTED_STAR),
("ARABIC LETTER DOTLESS BEH",ARABIC_LETTER_DOTLESS_BEH),
("ARABIC LETTER DOTLESS QAF",ARABIC_LETTER_DOTLESS_QAF),
("ARABIC LETTER SUPERSCRIPT ALEF",ARABIC_LETTER_SUPERSCRIPT_ALEF),
("ARABIC LETTER ALEF WASLA",ARABIC_LETTER_ALEF_WASLA),
("ARABIC LETTER ALEF WITH WAVY HAMZA ABOVE",ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE),
("ARABIC LETTER ALEF WITH WAVY HAMZA BELOW",ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW),
("ARABIC LETTER HIGH HAMZA",ARABIC_LETTER_HIGH_HAMZA),
("ARABIC LETTER HIGH HAMZA ALEF",ARABIC_LETTER_HIGH_HAMZA_ALEF),
("ARABIC LETTER HIGH HAMZA WAW",ARABIC_LETTER_HIGH_HAMZA_WAW),
("ARABIC LETTER U WITH HAMZA ABOVE",ARABIC_LETTER_U_WITH_HAMZA_ABOVE),
("ARABIC LETTER HIGH HAMZA YEH",ARABIC_LETTER_HIGH_HAMZA_YEH),
("ARABIC LETTER TTEH",ARABIC_LETTER_TTEH),
("ARABIC LETTER TTEHEH",ARABIC_LETTER_TTEHEH),
("ARABIC LETTER BEEH",ARABIC_LETTER_BEEH),
("ARABIC LETTER TEH WITH RING",ARABIC_LETTER_TEH_WITH_RING),
("ARABIC LETTER TEH WITH THREE DOTS ABOVE DOWNWARDS",ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS),
("ARABIC LETTER PEH",ARABIC_LETTER_PEH),
("ARABIC LETTER TEHEH",ARABIC_LETTER_TEHEH),
("ARABIC LETTER BEHEH",ARABIC_LETTER_BEHEH),
("ARABIC LETTER HAH WITH HAMZA ABOVE",ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE),
("ARABIC LETTER HAH WITH TWO DOTS VERTICAL ABOVE",ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE),
("ARABIC LETTER NYEH",ARABIC_LETTER_NYEH),
("ARABIC LETTER DYEH",ARABIC_LETTER_DYEH),
("ARABIC LETTER HAH WITH THREE DOTS ABOVE",ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER TCHEH",ARABIC_LETTER_TCHEH),
("ARABIC LETTER TCHEHEH",ARABIC_LETTER_TCHEHEH),
("ARABIC LETTER DDAL",ARABIC_LETTER_DDAL),
("ARABIC LETTER DAL WITH RING",ARABIC_LETTER_DAL_WITH_RING),
("ARABIC LETTER DAL WITH DOT BELOW",ARABIC_LETTER_DAL_WITH_DOT_BELOW),
("ARABIC LETTER DAL WITH DOT BELOW AND SMALL TAH",ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH),
("ARABIC LETTER DAHAL",ARABIC_LETTER_DAHAL),
("ARABIC LETTER DDAHAL",ARABIC_LETTER_DDAHAL),
("ARABIC LETTER DUL",ARABIC_LETTER_DUL),
("ARABIC LETTER DAL WITH THREE DOTS ABOVE DOWNWARDS",ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS),
("ARABIC LETTER DAL WITH FOUR DOTS ABOVE",ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE),
("ARABIC LETTER RREH",ARABIC_LETTER_RREH),
("ARABIC LETTER REH WITH SMALL V",ARABIC_LETTER_REH_WITH_SMALL_V),
("ARABIC LETTER REH WITH RING",ARABIC_LETTER_REH_WITH_RING),
("ARABIC LETTER REH WITH DOT BELOW",ARABIC_LETTER_REH_WITH_DOT_BELOW),
("ARABIC LETTER REH WITH SMALL V BELOW",ARABIC_LETTER_REH_WITH_SMALL_V_BELOW),
("ARABIC LETTER REH WITH DOT BELOW AND DOT ABOVE",ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE),
("ARABIC LETTER REH WITH TWO DOTS ABOVE",ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE),
("ARABIC LETTER JEH",ARABIC_LETTER_JEH),
("ARABIC LETTER REH WITH FOUR DOTS ABOVE",ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE),
("ARABIC LETTER SEEN WITH DOT BELOW AND DOT ABOVE",ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE),
("ARABIC LETTER SEEN WITH THREE DOTS BELOW",ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER SEEN WITH THREE DOTS BELOW AND THREE DOTS ABOVE",ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE),
("ARABIC LETTER SAD WITH TWO DOTS BELOW",ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW),
("ARABIC LETTER SAD WITH THREE DOTS ABOVE",ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER TAH WITH THREE DOTS ABOVE",ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER AIN WITH THREE DOTS ABOVE",ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER DOTLESS FEH",ARABIC_LETTER_DOTLESS_FEH),
("ARABIC LETTER FEH WITH DOT MOVED BELOW",ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW),
("ARABIC LETTER FEH WITH DOT BELOW",ARABIC_LETTER_FEH_WITH_DOT_BELOW),
("ARABIC LETTER VEH",ARABIC_LETTER_VEH),
("ARABIC LETTER FEH WITH THREE DOTS BELOW",ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER PEHEH",ARABIC_LETTER_PEHEH),
("ARABIC LETTER QAF WITH DOT ABOVE",ARABIC_LETTER_QAF_WITH_DOT_ABOVE),
("ARABIC LETTER QAF WITH THREE DOTS ABOVE",ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER KEHEH",ARABIC_LETTER_KEHEH),
("ARABIC LETTER SWASH KAF",ARABIC_LETTER_SWASH_KAF),
("ARABIC LETTER KAF WITH RING",ARABIC_LETTER_KAF_WITH_RING),
("ARABIC LETTER KAF WITH DOT ABOVE",ARABIC_LETTER_KAF_WITH_DOT_ABOVE),
("ARABIC LETTER NG",ARABIC_LETTER_NG),
("ARABIC LETTER KAF WITH THREE DOTS BELOW",ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER GAF",ARABIC_LETTER_GAF),
("ARABIC LETTER GAF WITH RING",ARABIC_LETTER_GAF_WITH_RING),
("ARABIC LETTER NGOEH",ARABIC_LETTER_NGOEH),
("ARABIC LETTER GAF WITH TWO DOTS BELOW",ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW),
("ARABIC LETTER GUEH",ARABIC_LETTER_GUEH),
("ARABIC LETTER GAF WITH THREE DOTS ABOVE",ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER LAM WITH SMALL V",ARABIC_LETTER_LAM_WITH_SMALL_V),
("ARABIC LETTER LAM WITH DOT ABOVE",ARABIC_LETTER_LAM_WITH_DOT_ABOVE),
("ARABIC LETTER LAM WITH THREE DOTS ABOVE",ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER LAM WITH THREE DOTS BELOW",ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER NOON WITH DOT BELOW",ARABIC_LETTER_NOON_WITH_DOT_BELOW),
("ARABIC LETTER NOON GHUNNA",ARABIC_LETTER_NOON_GHUNNA),
("ARABIC LETTER RNOON",ARABIC_LETTER_RNOON),
("ARABIC LETTER NOON WITH RING",ARABIC_LETTER_NOON_WITH_RING),
("ARABIC LETTER NOON WITH THREE DOTS ABOVE",ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE),
("ARABIC LETTER HEH DOACHASHMEE",ARABIC_LETTER_HEH_DOACHASHMEE),
("ARABIC LETTER TCHEH WITH DOT ABOVE",ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE),
("ARABIC LETTER HEH WITH YEH ABOVE",ARABIC_LETTER_HEH_WITH_YEH_ABOVE),
("ARABIC LETTER HEH GOAL",ARABIC_LETTER_HEH_GOAL),
("ARABIC LETTER HEH GOAL WITH HAMZA ABOVE",ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE),
("ARABIC LETTER TEH MARBUTA GOAL",ARABIC_LETTER_TEH_MARBUTA_GOAL),
("ARABIC LETTER WAW WITH RING",ARABIC_LETTER_WAW_WITH_RING),
("ARABIC LETTER KIRGHIZ OE",ARABIC_LETTER_KIRGHIZ_OE),
("ARABIC LETTER OE",ARABIC_LETTER_OE),
("ARABIC LETTER U",ARABIC_LETTER_U),
("ARABIC LETTER YU",ARABIC_LETTER_YU),
("ARABIC LETTER KIRGHIZ YU",ARABIC_LETTER_KIRGHIZ_YU),
("ARABIC LETTER WAW WITH TWO DOTS ABOVE",ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE),
("ARABIC LETTER VE",ARABIC_LETTER_VE),
("ARABIC LETTER FARSI YEH",ARABIC_LETTER_FARSI_YEH),
("ARABIC LETTER YEH WITH TAIL",ARABIC_LETTER_YEH_WITH_TAIL),
("ARABIC LETTER YEH WITH SMALL V",ARABIC_LETTER_YEH_WITH_SMALL_V),
("ARABIC LETTER WAW WITH DOT ABOVE",ARABIC_LETTER_WAW_WITH_DOT_ABOVE),
("ARABIC LETTER E",ARABIC_LETTER_E),
("ARABIC LETTER YEH WITH THREE DOTS BELOW",ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW),
("ARABIC LETTER YEH BARREE",ARABIC_LETTER_YEH_BARREE),
("ARABIC LETTER YEH BARREE WITH HAMZA ABOVE",ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE),
("ARABIC FULL STOP",ARABIC_FULL_STOP),
("ARABIC LETTER AE",ARABIC_LETTER_AE),
("ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA",ARABIC_SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA),
("ARABIC SMALL HIGH LIGATURE QAF WITH LAM WITH ALEF MAKSURA",ARABIC_SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA),
("ARABIC SMALL HIGH MEEM INITIAL FORM",ARABIC_SMALL_HIGH_MEEM_INITIAL_FORM),
("ARABIC SMALL HIGH LAM ALEF",ARABIC_SMALL_HIGH_LAM_ALEF),
("ARABIC SMALL HIGH JEEM",ARABIC_SMALL_HIGH_JEEM),
("ARABIC SMALL HIGH THREE DOTS",ARABIC_SMALL_HIGH_THREE_DOTS),
("ARABIC SMALL HIGH SEEN",ARABIC_SMALL_HIGH_SEEN),
("ARABIC END OF AYAH",ARABIC_END_OF_AYAH),
("ARABIC START OF RUB EL HIZB",ARABIC_START_OF_RUB_EL_HIZB),
("ARABIC SMALL HIGH ROUNDED ZERO",ARABIC_SMALL_HIGH_ROUNDED_ZERO),
("ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO",ARABIC_SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO),
("ARABIC SMALL HIGH DOTLESS HEAD OF KHAH",ARABIC_SMALL_HIGH_DOTLESS_HEAD_OF_KHAH),
("ARABIC SMALL HIGH MEEM ISOLATED FORM",ARABIC_SMALL_HIGH_MEEM_ISOLATED_FORM),
("ARABIC SMALL LOW SEEN",ARABIC_SMALL_LOW_SEEN),
("ARABIC SMALL HIGH MADDA",ARABIC_SMALL_HIGH_MADDA),
("ARABIC SMALL WAW",ARABIC_SMALL_WAW),
("ARABIC SMALL YEH",ARABIC_SMALL_YEH),
("ARABIC SMALL HIGH YEH",ARABIC_SMALL_HIGH_YEH),
("ARABIC SMALL HIGH NOON",ARABIC_SMALL_HIGH_NOON),
("ARABIC PLACE OF SAJDAH",ARABIC_PLACE_OF_SAJDAH),
("ARABIC EMPTY CENTRE LOW STOP",ARABIC_EMPTY_CENTRE_LOW_STOP),
("ARABIC EMPTY CENTRE HIGH STOP",ARABIC_EMPTY_CENTRE_HIGH_STOP),
("ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE",ARABIC_ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE),
("ARABIC SMALL LOW MEEM",ARABIC_SMALL_LOW_MEEM),
("ARABIC LETTER DAL WITH INVERTED V",ARABIC_LETTER_DAL_WITH_INVERTED_V),
("ARABIC LETTER REH WITH INVERTED V",ARABIC_LETTER_REH_WITH_INVERTED_V),
("EXTENDED ARABIC-INDIC DIGIT ZERO",EXTENDED_ARABIC_INDIC_DIGIT_ZERO),
("EXTENDED ARABIC-INDIC DIGIT ONE",EXTENDED_ARABIC_INDIC_DIGIT_ONE),
("EXTENDED ARABIC-INDIC DIGIT TWO",EXTENDED_ARABIC_INDIC_DIGIT_TWO),
("EXTENDED ARABIC-INDIC DIGIT THREE",EXTENDED_ARABIC_INDIC_DIGIT_THREE),
("EXTENDED ARABIC-INDIC DIGIT FOUR",EXTENDED_ARABIC_INDIC_DIGIT_FOUR),
("EXTENDED ARABIC-INDIC DIGIT FIVE",EXTENDED_ARABIC_INDIC_DIGIT_FIVE),
("EXTENDED ARABIC-INDIC DIGIT SIX",EXTENDED_ARABIC_INDIC_DIGIT_SIX),
("EXTENDED ARABIC-INDIC DIGIT SEVEN",EXTENDED_ARABIC_INDIC_DIGIT_SEVEN),
("EXTENDED ARABIC-INDIC DIGIT EIGHT",EXTENDED_ARABIC_INDIC_DIGIT_EIGHT),
("EXTENDED ARABIC-INDIC DIGIT NINE",EXTENDED_ARABIC_INDIC_DIGIT_NINE),
("ARABIC LETTER SHEEN WITH DOT BELOW",ARABIC_LETTER_SHEEN_WITH_DOT_BELOW),
("ARABIC LETTER DAD WITH DOT BELOW",ARABIC_LETTER_DAD_WITH_DOT_BELOW),
("ARABIC LETTER GHAIN WITH DOT BELOW",ARABIC_LETTER_GHAIN_WITH_DOT_BELOW),
("ARABIC SIGN SINDHI AMPERSAND",ARABIC_SIGN_SINDHI_AMPERSAND),
("ARABIC SIGN SINDHI POSTPOSITION MEN",ARABIC_SIGN_SINDHI_POSTPOSITION_MEN),
("ARABIC LETTER HEH WITH INVERTED V",ARABIC_LETTER_HEH_WITH_INVERTED_V))

##
# Arabic Unicode Set
##
ARABIC_UNICODE = (ARABIC_NUMBER_SIGN,
									ARABIC_SIGN_SANAH,
									ARABIC_FOOTNOTE_MARKER,
									ARABIC_SIGN_SAFHA,
									ARABIC_SIGN_SAMVAT,
									ARABIC_INDIC_CUBE_ROOT,
									ARABIC_INDIC_FOURTH_ROOT,
									ARABIC_RAY,
									ARABIC_INDIC_PER_MILLE_SIGN,
									ARABIC_INDIC_PER_TEN_THOUSAND_SIGN,
									AFGHANI_SIGN,
									ARABIC_COMMA,
									ARABIC_DATE_SEPARATOR,
									ARABIC_POETIC_VERSE_SIGN,
									ARABIC_SIGN_MISRA,
									ARABIC_SIGN_SALLALLAHOU_ALAYHE_WASSALLAM,
									ARABIC_SIGN_ALAYHE_ASSALLAM,
									ARABIC_SIGN_RAHMATULLAH_ALAYHE,
									ARABIC_SIGN_RADI_ALLAHOU_ANHU,
									ARABIC_SIGN_TAKHALLUS,
									ARABIC_SMALL_HIGH_TAH,
									ARABIC_SMALL_HIGH_LIGATURE_ALEF_WITH_LAM_WITH_YEH,
									ARABIC_SMALL_HIGH_ZAIN,
									ARABIC_SMALL_FATHA,
									ARABIC_SMALL_DAMMA,
									ARABIC_SMALL_KASRA,
									ARABIC_SEMICOLON,
									ARABIC_LETTER_MARK,
									ARABIC_TRIPLE_DOT_PUNCTUATION_MARK,
									ARABIC_QUESTION_MARK,
									ARABIC_LETTER_KASHMIRI_YEH,
									ARABIC_LETTER_HAMZA,
									ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE,
									ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW,
									ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_ALEF,
									ARABIC_LETTER_BEH,
									ARABIC_LETTER_TEH_MARBUTA,
									ARABIC_LETTER_TEH,
									ARABIC_LETTER_THEH,
									ARABIC_LETTER_JEEM,
									ARABIC_LETTER_HAH,
									ARABIC_LETTER_KHAH,
									ARABIC_LETTER_DAL,
									ARABIC_LETTER_THAL,
									ARABIC_LETTER_REH,
									ARABIC_LETTER_ZAIN,
									ARABIC_LETTER_SEEN,
									ARABIC_LETTER_SHEEN,
									ARABIC_LETTER_SAD,
									ARABIC_LETTER_DAD,
									ARABIC_LETTER_TAH,
									ARABIC_LETTER_ZAH,
									ARABIC_LETTER_AIN,
									ARABIC_LETTER_GHAIN,
									ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V,
									ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE,
									ARABIC_TATWEEL,
									ARABIC_LETTER_FEH,
									ARABIC_LETTER_QAF,
									ARABIC_LETTER_KAF,
									ARABIC_LETTER_LAM,
									ARABIC_LETTER_MEEM,
									ARABIC_LETTER_NOON,
									ARABIC_LETTER_HEH,
									ARABIC_LETTER_WAW,
									ARABIC_LETTER_ALEF_MAKSURA,
									ARABIC_LETTER_YEH,
									ARABIC_FATHATAN,
									ARABIC_DAMMATAN,
									ARABIC_KASRATAN,
									ARABIC_FATHA,
									ARABIC_DAMMA,
									ARABIC_KASRA,
									ARABIC_SHADDA,
									ARABIC_SUKUN,
									ARABIC_MADDAH_ABOVE,
									ARABIC_HAMZA_ABOVE,
									ARABIC_HAMZA_BELOW,
									ARABIC_SUBSCRIPT_ALEF,
									ARABIC_INVERTED_DAMMA,
									ARABIC_MARK_NOON_GHUNNA,
									ARABIC_ZWARAKAY,
									ARABIC_VOWEL_SIGN_SMALL_V_ABOVE,
									ARABIC_VOWEL_SIGN_INVERTED_SMALL_V_ABOVE,
									ARABIC_VOWEL_SIGN_DOT_BELOW,
									ARABIC_REVERSED_DAMMA,
									ARABIC_FATHA_WITH_TWO_DOTS,
									ARABIC_WAVY_HAMZA_BELOW,
									ARABIC_INDIC_DIGIT_ZERO,
									ARABIC_INDIC_DIGIT_ONE,
									ARABIC_INDIC_DIGIT_TWO,
									ARABIC_INDIC_DIGIT_THREE,
									ARABIC_INDIC_DIGIT_FOUR,
									ARABIC_INDIC_DIGIT_FIVE,
									ARABIC_INDIC_DIGIT_SIX,
									ARABIC_INDIC_DIGIT_SEVEN,
									ARABIC_INDIC_DIGIT_EIGHT,
									ARABIC_INDIC_DIGIT_NINE,
									ARABIC_PERCENT_SIGN,
									ARABIC_DECIMAL_SEPARATOR,
									ARABIC_THOUSANDS_SEPARATOR,
									ARABIC_FIVE_POINTED_STAR,
									ARABIC_LETTER_DOTLESS_BEH,
									ARABIC_LETTER_DOTLESS_QAF,
									ARABIC_LETTER_SUPERSCRIPT_ALEF,
									ARABIC_LETTER_ALEF_WASLA,
									ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE,
									ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW,
									ARABIC_LETTER_HIGH_HAMZA,
									ARABIC_LETTER_HIGH_HAMZA_ALEF,
									ARABIC_LETTER_HIGH_HAMZA_WAW,
									ARABIC_LETTER_U_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_HIGH_HAMZA_YEH,
									ARABIC_LETTER_TTEH,
									ARABIC_LETTER_TTEHEH,
									ARABIC_LETTER_BEEH,
									ARABIC_LETTER_TEH_WITH_RING,
									ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS,
									ARABIC_LETTER_PEH,
									ARABIC_LETTER_TEHEH,
									ARABIC_LETTER_BEHEH,
									ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE,
									ARABIC_LETTER_NYEH,
									ARABIC_LETTER_DYEH,
									ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_TCHEH,
									ARABIC_LETTER_TCHEHEH,
									ARABIC_LETTER_DDAL,
									ARABIC_LETTER_DAL_WITH_RING,
									ARABIC_LETTER_DAL_WITH_DOT_BELOW,
									ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH,
									ARABIC_LETTER_DAHAL,
									ARABIC_LETTER_DDAHAL,
									ARABIC_LETTER_DUL,
									ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS,
									ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE,
									ARABIC_LETTER_RREH,
									ARABIC_LETTER_REH_WITH_SMALL_V,
									ARABIC_LETTER_REH_WITH_RING,
									ARABIC_LETTER_REH_WITH_DOT_BELOW,
									ARABIC_LETTER_REH_WITH_SMALL_V_BELOW,
									ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE,
									ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_JEH,
									ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE,
									ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE,
									ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE,
									ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW,
									ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_DOTLESS_FEH,
									ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW,
									ARABIC_LETTER_FEH_WITH_DOT_BELOW,
									ARABIC_LETTER_VEH,
									ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_PEHEH,
									ARABIC_LETTER_QAF_WITH_DOT_ABOVE,
									ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_KEHEH,
									ARABIC_LETTER_SWASH_KAF,
									ARABIC_LETTER_KAF_WITH_RING,
									ARABIC_LETTER_KAF_WITH_DOT_ABOVE,
									ARABIC_LETTER_NG,
									ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_GAF,
									ARABIC_LETTER_GAF_WITH_RING,
									ARABIC_LETTER_NGOEH,
									ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW,
									ARABIC_LETTER_GUEH,
									ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_LAM_WITH_SMALL_V,
									ARABIC_LETTER_LAM_WITH_DOT_ABOVE,
									ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_NOON_WITH_DOT_BELOW,
									ARABIC_LETTER_NOON_GHUNNA,
									ARABIC_LETTER_RNOON,
									ARABIC_LETTER_NOON_WITH_RING,
									ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE,
									ARABIC_LETTER_HEH_DOACHASHMEE,
									ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE,
									ARABIC_LETTER_HEH_WITH_YEH_ABOVE,
									ARABIC_LETTER_HEH_GOAL,
									ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_TEH_MARBUTA_GOAL,
									ARABIC_LETTER_WAW_WITH_RING,
									ARABIC_LETTER_KIRGHIZ_OE,
									ARABIC_LETTER_OE,
									ARABIC_LETTER_U,
									ARABIC_LETTER_YU,
									ARABIC_LETTER_KIRGHIZ_YU,
									ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_VE,
									ARABIC_LETTER_FARSI_YEH,
									ARABIC_LETTER_YEH_WITH_TAIL,
									ARABIC_LETTER_YEH_WITH_SMALL_V,
									ARABIC_LETTER_WAW_WITH_DOT_ABOVE,
									ARABIC_LETTER_E,
									ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_YEH_BARREE,
									ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE,
									ARABIC_FULL_STOP,
									ARABIC_LETTER_AE,
									ARABIC_SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA,
									ARABIC_SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA,
									ARABIC_SMALL_HIGH_MEEM_INITIAL_FORM,
									ARABIC_SMALL_HIGH_LAM_ALEF,
									ARABIC_SMALL_HIGH_JEEM,
									ARABIC_SMALL_HIGH_THREE_DOTS,
									ARABIC_SMALL_HIGH_SEEN,
									ARABIC_END_OF_AYAH,
									ARABIC_START_OF_RUB_EL_HIZB,
									ARABIC_SMALL_HIGH_ROUNDED_ZERO,
									ARABIC_SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO,
									ARABIC_SMALL_HIGH_DOTLESS_HEAD_OF_KHAH,
									ARABIC_SMALL_HIGH_MEEM_ISOLATED_FORM,
									ARABIC_SMALL_LOW_SEEN,
									ARABIC_SMALL_HIGH_MADDA,
									ARABIC_SMALL_WAW,
									ARABIC_SMALL_YEH,
									ARABIC_SMALL_HIGH_YEH,
									ARABIC_SMALL_HIGH_NOON,
									ARABIC_PLACE_OF_SAJDAH,
									ARABIC_EMPTY_CENTRE_LOW_STOP,
									ARABIC_EMPTY_CENTRE_HIGH_STOP,
									ARABIC_ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE,
									ARABIC_SMALL_LOW_MEEM,
									ARABIC_LETTER_DAL_WITH_INVERTED_V,
									ARABIC_LETTER_REH_WITH_INVERTED_V,
									EXTENDED_ARABIC_INDIC_DIGIT_ZERO,
									EXTENDED_ARABIC_INDIC_DIGIT_ONE,
									EXTENDED_ARABIC_INDIC_DIGIT_TWO,
									EXTENDED_ARABIC_INDIC_DIGIT_THREE,
									EXTENDED_ARABIC_INDIC_DIGIT_FOUR,
									EXTENDED_ARABIC_INDIC_DIGIT_FIVE,
									EXTENDED_ARABIC_INDIC_DIGIT_SIX,
									EXTENDED_ARABIC_INDIC_DIGIT_SEVEN,
									EXTENDED_ARABIC_INDIC_DIGIT_EIGHT,
									EXTENDED_ARABIC_INDIC_DIGIT_NINE,
									ARABIC_LETTER_SHEEN_WITH_DOT_BELOW,
									ARABIC_LETTER_DAD_WITH_DOT_BELOW,
									ARABIC_LETTER_GHAIN_WITH_DOT_BELOW,
									ARABIC_SIGN_SINDHI_AMPERSAND,
									ARABIC_SIGN_SINDHI_POSTPOSITION_MEN,
									ARABIC_LETTER_HEH_WITH_INVERTED_V)

#Arabic Subtending Marks
ARABIC_SUBTENDING_MARKS = (ARABIC_NUMBER_SIGN,
													 ARABIC_SIGN_SANAH,
													 ARABIC_FOOTNOTE_MARKER,
													 ARABIC_SIGN_SAFHA,
													 ARABIC_SIGN_SAMVAT)

#Arabic Radix Symbols
ARABIC_RADIX_SYMBOL = (ARABIC_INDIC_CUBE_ROOT,
											 ARABIC_INDIC_FOURTH_ROOT)


#Arabic Letterlike Symbols
ARABIC_LETTER_SYMBOL = (ARABIC_RAY)


#Arabic Punctuation
ARABIC_PUNCTUATION = (ARABIC_INDIC_PER_MILLE_SIGN,
											ARABIC_INDIC_PER_TEN_THOUSAND_SIGN,
											ARABIC_COMMA,
											ARABIC_DATE_SEPARATOR,
											ARABIC_SEMICOLON,
											ARABIC_TRIPLE_DOT_PUNCTUATION_MARK,
											ARABIC_QUESTION_MARK,
											ARABIC_PERCENT_SIGN,
											ARABIC_DECIMAL_SEPARATOR,
											ARABIC_THOUSANDS_SEPARATOR,
											ARABIC_FIVE_POINTED_STAR,
											ARABIC_EXCLAMATION_MARK,
											ARABIC_FULL_STOP,
											)


#Arabic Currency Sign
ARABIC_CURRENCY_SIGN = (AFGHANI_SIGN)


#Arabic Poetic Marks
ARABIC_POETIC_MARKS = (ARABIC_POETIC_VERSE_SIGN,
											 ARABIC_SIGN_MISRA)

#Arabic Honorifics
ARABIC_HONORIFICS = (ARABIC_SIGN_SALLALLAHOU_ALAYHE_WASSALLAM,
										 ARABIC_SIGN_ALAYHE_ASSALLAM,
	                   ARABIC_SIGN_RADI_ALLAHOU_ANHU,
	                   ARABIC_SIGN_TAKHALLUS)


#Arabic Quranic Annotation Sign
ARAIBC_QURANIC_ANNOTATION_SIGN = (ARABIC_SMALL_HIGH_TAH,
																  ARABIC_SMALL_HIGH_ZAIN,
																  ARABIC_SMALL_FATHA,
																  ARABIC_SMALL_DAMMA,
																  ARABIC_SMALL_KASRA,
																  ARABIC_SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA,
																  ARABIC_SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA,
																  ARABIC_SMALL_HIGH_MEEM_INITIAL_FORM,
																  ARABIC_SMALL_HIGH_LAM_ALEF,
																  ARABIC_SMALL_HIGH_JEEM,
																  ARABIC_SMALL_HIGH_THREE_DOTS,
																  ARABIC_SMALL_HIGH_SEEN,
																  ARABIC_END_OF_AYAH,
																  ARABIC_START_OF_RUB_EL_HIZB,
																  ARABIC_SMALL_HIGH_ROUNDED_ZERO,
																  ARABIC_SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO,
																  ARABIC_SMALL_HIGH_DOTLESS_HEAD_OF_KHAH,
																  ARABIC_SMALL_HIGH_MEEM_ISOLATED_FORM,
																  ARABIC_SMALL_LOW_SEEN,
																  ARABIC_SMALL_HIGH_MADDA,
																  ARABIC_SMALL_WAW,
																  ARABIC_SMALL_YEH,
																  ARABIC_SMALL_HIGH_YEH,
																  ARABIC_SMALL_HIGH_NOON,
																  ARABIC_PLACE_OF_SAJDAH,
																  ARABIC_EMPTY_CENTRE_LOW_STOP,
																  ARABIC_EMPTY_CENTRE_HIGH_STOP,
																  ARABIC_ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE)


#Arabic Format Character
ARABIC_FORMAT_CHARACTER = (ARABIC_LETTER_MARK)

#Arabic Addition For Kashmiri
ARABIC_ADDITION_FOR_KASHMIRI = (ARABIC_LETTER_KASHMIRI_YEH)


#Arabic Letters based on ISO 8859-6
ARABIC_LETTERS = (
									ARABIC_LETTER_HAMZA,
									ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE,
									ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW,
									ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE,
									ARABIC_LETTER_ALEF,
									ARABIC_LETTER_BEH,
									ARABIC_LETTER_TEH_MARBUTA,
									ARABIC_LETTER_TEH,
									ARABIC_LETTER_THEH,
									ARABIC_LETTER_JEEM,
									ARABIC_LETTER_HAH,
									ARABIC_LETTER_KHAH,
									ARABIC_LETTER_DAL,
									ARABIC_LETTER_THAL,
									ARABIC_LETTER_REH,
									ARABIC_LETTER_ZAIN,
									ARABIC_LETTER_SEEN,
									ARABIC_LETTER_SHEEN,
									ARABIC_LETTER_SAD,
									ARABIC_LETTER_DAD,
									ARABIC_LETTER_TAH,
									ARABIC_LETTER_ZAH,
									ARABIC_LETTER_AIN,
									ARABIC_LETTER_GHAIN,
									ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW,
									ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V,
									ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE,
									ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE,
									ARABIC_TATWEEL,
									ARABIC_LETTER_FEH,
									ARABIC_LETTER_QAF,
									ARABIC_LETTER_KAF,
									ARABIC_LETTER_LAM,
									ARABIC_LETTER_MEEM,
									ARABIC_LETTER_NOON,
									ARABIC_LETTER_HEH,
									ARABIC_LETTER_WAW,
									ARABIC_LETTER_ALEF_MAKSURA,
									ARABIC_LETTER_YEH)

#Points from ISO 8859-6 (Tashkeel)
ARABIC_TASHKEEL = (ARABIC_DAMMA,
									 ARABIC_FATHA,
									 ARABIC_KASRA,
									 ARABIC_SUKUN,
									 ARABIC_FATHATAN,
									 ARABIC_DAMMATAN,
									 ARABIC_KASRATAN,
									 ARABIC_SHADDA,
									 ARABIC_MADDAH_ABOVE,
									 ARABIC_SMALL_HIGH_MADDA)


#Arabic Special Combining Marks
ARABIC_COMBINE_MARKS = (ARABIC_SUBSCRIPT_ALEF,
												ARABIC_INVERTED_DAMMA,
												ARABIC_MARK_NOON_GHUNNA,
												ARABIC_ZWARAKAY,
												ARABIC_VOWEL_SIGN_SMALL_V_ABOVE,
												ARABIC_VOWEL_SIGN_INVERTED_SMALL_V_ABOVE,
												ARABIC_VOWEL_SIGN_DOT_BELOW,
												ARABIC_REVERSED_DAMMA,
												ARABIC_FATHA_WITH_TWO_DOTS,
												ARABIC_WAVY_HAMZA_BELOW)


#Arabic Point (A vowel Sign (Alef))
ARABIC_VOWEL_SIGN = (ARABIC_LETTER_SUPERSCRIPT_ALEF)


#Extended Arabic Letters
ARABIC_EXTENDED_LETTERS = (ARABIC_LETTER_ALEF_WASLA,
													ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE,
													ARABIC_LETTER_HIGH_HAMZA,
													ARABIC_LETTER_HIGH_HAMZA_ALEF,
													ARABIC_LETTER_HIGH_HAMZA_WAW,
													ARABIC_LETTER_U_WITH_HAMZA_ABOVE,
													ARABIC_LETTER_HIGH_HAMZA_YEH,
													ARABIC_LETTER_TTEH,
													ARABIC_LETTER_BEEH,
													ARABIC_LETTER_TEH_WITH_RING,
													ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS,
													ARABIC_LETTER_PEH,
													ARABIC_LETTER_TEHEH,
													ARABIC_LETTER_BEHEH,
													ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE,
													ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE,
													ARABIC_LETTER_NYEH,
													ARABIC_LETTER_DYEH,
													ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_TCHEH,
													ARABIC_LETTER_TCHEHEH,
													ARABIC_LETTER_DDAL,
													ARABIC_LETTER_DAL_WITH_RING,
													ARABIC_LETTER_DAL_WITH_DOT_BELOW,
													ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH,
													ARABIC_LETTER_DAHAL,
													ARABIC_LETTER_DDAHAL,
													ARABIC_LETTER_DUL,
													ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS,
													ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE,
													ARABIC_LETTER_RREH,
													ARABIC_LETTER_REH_WITH_SMALL_V,
													ARABIC_LETTER_REH_WITH_SMALL_V,
													ARABIC_LETTER_REH_WITH_RING,
													ARABIC_LETTER_REH_WITH_DOT_BELOW,
													ARABIC_LETTER_REH_WITH_SMALL_V_BELOW,
													ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE,
													ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE,
													ARABIC_LETTER_JEH,
													ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE,
													ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE,
													ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW,
													ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE,
													ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW,
													ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_DOTLESS_FEH,
													ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW,
													ARABIC_LETTER_FEH_WITH_DOT_BELOW,
													ARABIC_LETTER_VEH,
													ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW,
													ARABIC_LETTER_PEHEH,
													ARABIC_LETTER_QAF_WITH_DOT_ABOVE,
													ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_KEHEH,
													ARABIC_LETTER_SWASH_KAF,
													ARABIC_LETTER_KAF_WITH_RING,
													ARABIC_LETTER_KAF_WITH_DOT_ABOVE,
													ARABIC_LETTER_NG,
													ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW,
													ARABIC_LETTER_GAF,
													ARABIC_LETTER_GAF_WITH_RING,
													ARABIC_LETTER_NGOEH,
													ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW,
													ARABIC_LETTER_GUEH,
													ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_LAM_WITH_SMALL_V,
													ARABIC_LETTER_LAM_WITH_DOT_ABOVE,
													ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW,
													ARABIC_LETTER_NOON_WITH_DOT_BELOW,
													ARABIC_LETTER_NOON_GHUNNA,
													ARABIC_LETTER_RNOON,
													ARABIC_LETTER_NOON_WITH_RING,
													ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE,
													ARABIC_LETTER_HEH_DOACHASHMEE,
													ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE,
													ARABIC_LETTER_HEH_WITH_YEH_ABOVE,
													ARABIC_LETTER_HEH_GOAL,
													ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE,
													ARABIC_LETTER_TEH_MARBUTA_GOAL,
													ARABIC_LETTER_WAW_WITH_RING,
													ARABIC_LETTER_KIRGHIZ_OE,
													ARABIC_LETTER_OE,
													ARABIC_LETTER_U,
													ARABIC_LETTER_YU,
													ARABIC_LETTER_KIRGHIZ_YU,
													ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE,
													ARABIC_LETTER_VE,
													ARABIC_LETTER_FARSI_YEH,
													ARABIC_LETTER_YEH_WITH_TAIL,
													ARABIC_LETTER_YEH_WITH_SMALL_V,
													ARABIC_LETTER_WAW_WITH_DOT_ABOVE,
													ARABIC_LETTER_E,
													ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW,
													ARABIC_LETTER_YEH_BARREE,
													ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE,
													ARABIC_LETTER_AE,
													ARABIC_LETTER_DAL_WITH_INVERTED_V,
													ARABIC_LETTER_REH_WITH_INVERTED_V,
													ARABIC_LETTER_SHEEN_WITH_DOT_BELOW,
													ARABIC_LETTER_DAD_WITH_DOT_BELOW,
													ARABIC_LETTER_GHAIN_WITH_DOT_BELOW,
													ARABIC_LETTER_HEH_WITH_INVERTED_V)


#Arabic Deprecated Letter
ARABIC_DEPRECATED_LETTER = (ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW)

#Arabic Extended Letter for Pakari
ARABIC_EXT_LETTERS_PARKARI = (ARABIC_LETTER_DAL_WITH_INVERTED_V,
															ARABIC_LETTER_REH_WITH_INVERTED_V,
															ARABIC_LETTER_HEH_WITH_INVERTED_V)

#Eastern Arabic Indic Digits
ARABIC_INDIC_EASTERN_DIGITS = (EXTENDED_ARABIC_INDIC_DIGIT_ONE,
															 EXTENDED_ARABIC_INDIC_DIGIT_TWO,
															 EXTENDED_ARABIC_INDIC_DIGIT_THREE,
															 EXTENDED_ARABIC_INDIC_DIGIT_FOUR,
															 EXTENDED_ARABIC_INDIC_DIGIT_FIVE,
															 EXTENDED_ARABIC_INDIC_DIGIT_SIX,
															 EXTENDED_ARABIC_INDIC_DIGIT_SEVEN,
															 EXTENDED_ARABIC_INDIC_DIGIT_EIGHT,
															 EXTENDED_ARABIC_INDIC_DIGIT_NINE)

#Arabic Signs for Sindhi
ARABIC_SIGNS_SINDHI = (ARABIC_SIGN_SINDHI_AMPERSAND,
											 ARABIC_SIGN_SINDHI_POSTPOSITION_MEN)


##
# Ligatures 
##
ARABIC_LETTER_LAM_ALEF = u"\ufefb"
ARABIC_LETTER_LAM_ALEF_MADDA_ABOVE = u"\ufef5"
ARABIC_LETTER_LAM_ALEF_HAMZA_ABOVE = u"\ufef7"
ARABIC_LETTER_LAM_ALEF_HAMZA_BELLOW = u"\ufef9"


#Arabic Radix Symbols
ARABIC_RADIX_SYMBOL = (ARABIC_INDIC_CUBE_ROOT,
											 ARABIC_INDIC_FOURTH_ROOT)

#Huruf Shamsia
ARABIC_SOLAR_LETTERS = (ARABIC_LETTER_TEH,
												ARABIC_LETTER_THEH,
												ARABIC_LETTER_DAL,
												ARABIC_LETTER_REH,
												ARABIC_LETTER_ZAIN,
												ARABIC_LETTER_SEEN,
												ARABIC_LETTER_SHEEN,
												ARABIC_LETTER_SAD,
												ARABIC_LETTER_DAD,
												ARABIC_LETTER_TAH,
												ARABIC_LETTER_ZAH,
												ARABIC_LETTER_LAM,
												ARABIC_LETTER_NOON)

#Huruf Qamaria
ARABIC_LUNAR_LETTERS = (ARABIC_LETTER_ALEF,
												ARABIC_LETTER_BEH,
												ARABIC_LETTER_JEEM,
												ARABIC_LETTER_KHAH,
												ARABIC_LETTER_AIN,
												ARABIC_LETTER_GHAIN,
												ARABIC_LETTER_FEH,
												ARABIC_LETTER_QAF,
												ARABIC_LETTER_KAF,
												ARABIC_LETTER_MEEM,
												ARABIC_LETTER_WAW,
												ARABIC_LETTER_HEH,
												ARABIC_LETTER_YEH)
##
#Arabic Group Alef letters
##
ARABIC_ALEF_GROUP= (ARABIC_LETTER_HAMZA,
					ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE,
					ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
					ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE,
					ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW,
					ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE,
					ARABIC_LETTER_ALEF)

##
#Arabic Prepositions
##
ARABIC_PREP_MEN = ARABIC_LETTER_MEEM + ARABIC_LETTER_NOON
ARABIC_PREP_ELA = ARABIC_LETTER_ALEF + ARABIC_LETTER_LAM + ARABIC_LETTER_ALEF_MAKSURA
ARABIC_PREP_HATTA = ARABIC_LETTER_HAH + ARABIC_LETTER_TEH + ARABIC_LETTER_ALEF_MAKSURA
ARABIC_PREP_KHALA = ARABIC_LETTER_KHAH + ARABIC_LETTER_LAM + ARABIC_LETTER_ALEF
ARABIC_PREP_HASHA = ARABIC_LETTER_HAH + ARABIC_LETTER_SHEEN + ARABIC_LETTER_ALEF_MAKSURA
ARABIC_PREP_ADA = ARABIC_LETTER_AIN + ARABIC_LETTER_DAL + ARABIC_LETTER_ALEF
ARABIC_PREP_FE = ARABIC_LETTER_FEH + ARABIC_LETTER_YEH
ARABIC_PREP_AN = ARABIC_LETTER_AIN + ARABIC_LETTER_NOON
ARABIC_PREP_ALA = ARABIC_LETTER_AIN + ARABIC_LETTER_LAM + ARABIC_LETTER_ALEF_MAKSURA
ARABIC_PREP_MUTH = ARABIC_LETTER_MEEM + ARABIC_LETTER_THAL
ARABIC_PREP_MUNTHO = ARABIC_LETTER_MEEM + ARABIC_LETTER_NOON + ARABIC_LETTER_THAL
ARABIC_PREP_LAM = ARABIC_LETTER_LAM
ARABIC_PREP_KAY = ARABIC_LETTER_KAF + ARABIC_LETTER_YEH
ARABIC_PREP_WAW = ARABIC_LETTER_WAW
ARABIC_PREP_TA = ARABIC_LETTER_TEH
ARABIC_PREP_KAF = ARABIC_LETTER_KAF
ARABIC_PREP_BA = ARABIC_LETTER_BEH
ARABIC_PREP_LALLA = ARABIC_LETTER_LAM + ARABIC_LETTER_AIN + ARABIC_LETTER_LAM
ARABIC_PREP_TA = ARABIC_LETTER_TEH
ARABIC_PREP_SAWFA = ARABIC_LETTER_SEEN+ARABIC_LETTER_WAW+ARABIC_LETTER_FEH
#PLUS SHADDA
ARABIC_PREP_MATA = ARABIC_LETTER_MEEM + ARABIC_LETTER_TEH + ARABIC_LETTER_ALEF_MAKSURA
ARABIC_PREP_RUBBA = ARABIC_LETTER_REH + ARABIC_LETTER_BEH
#PLUS SHADDA

#ARABIC PARTICLES

ARABIC_ALEF_LAM = ARABIC_LETTER_ALEF + ARABIC_LETTER_LAM
ARABIC_TEN_NOUNS = (ARABIC_LETTER_ALEF+ARABIC_LETTER_SEEN+ARABIC_LETTER_MEEM, 
		ARABIC_LETTER_ALEF+ARABIC_LETTER_SEEN+ARABIC_LETTER_TEH,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH_MARBUTA,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON+ARABIC_LETTER_MEEM,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_MEEM+ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_TEH_MARBUTA,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_THEH+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_TEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_NOON+" "+ARABIC_WORD_ALLAH)



#Word of God
ARABIC_WORD_ALLAH = u"\uFDF2"

#Haraket alTashkeel which guides how to pronounce the letter
ARABIC_TASHKEEL_HARAKAT = (ARABIC_DAMMA,
															ARABIC_FATHA,
															ARABIC_KASRA,
															ARABIC_SUKUN)

ARABIC_TASHKEEL_TANWEEN = (ARABIC_FATHATAN,
															ARABIC_DAMMATAN,
															ARABIC_KASRATAN)

#Arabic Tashkeel Thawabit is shadda, mad, wasl, qate'
#_TODO_:Hamz

ARABIC_TASHKEEL_THAWABIT = (ARABIC_SHADDA,
															 ARABIC_MADDAH_ABOVE,
															 ARABIC_SMALL_HIGH_MADDA)

ARABIC_SHORT_SPOKEN_VOWELS = (ARABIC_FATHA,
																 ARABIC_DAMMA,
																 ARABIC_KASRA)


ARABIC_LONG_SPOKEN_VOWELS = (ARABIC_FATHA+ARABIC_LETTER_ALEF,
																ARABIC_FATHA+ARABIC_LETTER_ALEF_MAKSURA,
																ARABIC_DAMMA+ARABIC_LETTER_WAW,
																ARABIC_KASRA+ARABIC_LETTER_YEH)



ARABIC_LONG_NONSPOKEN_VOWELS = (ARABIC_LETTER_ALEF,
																	 ARABIC_LETTER_ALEF_MAKSURA,
																	 ARABIC_LETTER_WAW,
																	 ARABIC_LETTER_YEH)


ARABIC_DIPHTHONG = (ARABIC_FATHA+ARABIC_LETTER_YEH,
											 ARABIC_FATHA+ARABIC_LETTER_WAW)



