# -*- encoding: utf-8 -*-
##############################################################
##  Author: Abdulmumen Naas
##	Description: Arabic Natural Language Processor (Kalam-lp)
##	Version: 0.0.1
##	Copyright (c) 2014 Abdulmumen Naas
#############################################################

from alefba import *

#Constantns
#DEMOSTRATIVES
DEM = (ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_THAL+ARABIC_LETTER_HEH,
				
				ARABIC_LETTER_HEH+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_HEH+ARABIC_LETTER_THAL+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,
				
				ARABIC_LETTER_HEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_TEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_HEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_TEH+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,

				ARABIC_LETTER_HEH+ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE+ARABIC_LETTER_LAM+ARABIC_LETTER_ALEF+ARABIC_LETTER_HAMZA,			
				)

DEMLOC = (ARABIC_LETTER_HEH+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF+ARABIC_LETTER_KAF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_KAF)
		
#Relatives nouns		
REL = (ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_THAL+ARABIC_LETTER_YEH,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_TEH+ARABIC_LETTER_YEH,
				
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM+ARABIC_LETTER_TEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM+ARABIC_LETTER_TEH+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM+ARABIC_LETTER_ALEF+ARABIC_LETTER_TEH+ARABIC_LETTER_YEH,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM+ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE+ARABIC_LETTER_YEH,)

#Personal Pronouns
PPRON1 = (ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_NOON+ARABIC_LETTER_HAH+ARABIC_LETTER_NOON)


PPRON2 = (ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH,

				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_MEEM,)

PPRON3 = (ARABIC_LETTER_HEH+ARABIC_LETTER_WAW,
				ARABIC_LETTER_HEH+ARABIC_LETTER_YEH,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_HEH+ARABIC_LETTER_NOON,)

#Possessive Pronouns
POSPRON = (ARABIC_LETTER_YEH,
				ARABIC_LETTER_KAF,
				ARABIC_LETTER_HEH,
				ARABIC_LETTER_HEH+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_KAF+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_KAF+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_KAF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_HEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM)

POSPRON1 = (ARABIC_LETTER_YEH,
		ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF)

POSPRON2 = (ARABIC_LETTER_KAF+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_KAF+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_KAF+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_KAF+ARABIC_LETTER_NOON,)

POSPRON3 = (ARABIC_LETTER_HEH,
				ARABIC_LETTER_HEH+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_HEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM)

CE_SF = (ARABIC_LETTER_TEH_MARBUTA,)
CE_DM = (ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,)
CE_DF = (ARABIC_LETTER_TEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,)
CE_PM = (ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,)
CE_PF = (ARABIC_LETTER_ALEF+ARABIC_LETTER_TEH,)

#Prepositions
PREP = (ARABIC_PREP_MEN, 
				ARABIC_PREP_ELA, 
				ARABIC_PREP_HATTA,
				ARABIC_PREP_KHALA,
				ARABIC_PREP_HASHA,
				ARABIC_PREP_ADA,
				ARABIC_PREP_FE,
				ARABIC_PREP_AN,
				ARABIC_PREP_ALA,
				ARABIC_PREP_MUTH,
				ARABIC_PREP_MUNTHO,
				ARABIC_PREP_KAY,
				ARABIC_PREP_WAW,
				ARABIC_PREP_TA,
				ARABIC_PREP_KAF,
				ARABIC_PREP_BA,
				ARABIC_PREP_LALLA,
				ARABIC_PREP_MATA)

PVSOLO = (ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_ALEF,
		ARABIC_LETTER_TEH,
		ARABIC_LETTER_NOON,
		ARABIC_LETTER_YEH,)
#Kana and sisters
KANA = (ARABIC_LETTER_KAF+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_LAM+ARABIC_LETTER_YEH+ARABIC_LETTER_SEEN,
				ARABIC_LETTER_SAD+ARABIC_LETTER_ALEF+ARABIC_LETTER_REH,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_SAD+ARABIC_LETTER_BEH+ARABIC_LETTER_HAH,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_SAD+ARABIC_LETTER_BEH+ARABIC_LETTER_HAH,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_DAD+ARABIC_LETTER_HAH+ARABIC_LETTER_ALEF_MAKSURA,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_DAD+ARABIC_LETTER_HEH+ARABIC_LETTER_ALEF_MAKSURA,

				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_MEEM+ARABIC_LETTER_SEEN+ARABIC_LETTER_ALEF_MAKSURA,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_MEEM+ARABIC_LETTER_SEEN+ARABIC_LETTER_ALEF_MAKSURA,
				ARABIC_LETTER_ZAH+ARABIC_LETTER_LAM,
				ARABIC_LETTER_BEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_TEH,)


#Conjunctions
CONJ = (ARABIC_LETTER_WAW,
				ARABIC_LETTER_THEH+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_WAW,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_WAW,
				ARABIC_LETTER_FEH)
		 

#Accusative(INNA)
ACC = (ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_PREP_LALLA,
				ARABIC_LETTER_LAM+ARABIC_LETTER_KAF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_KAF+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_NOON,
				ARABIC_LETTER_LAM+ARABIC_LETTER_YEH+ARABIC_LETTER_TEH)
		 

#Expceptions
EXP = (ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_LAM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_GHAIN,ARABIC_LETTER_YEH+ARABIC_LETTER_REH,
				ARABIC_PREP_KHALA,
				ARABIC_PREP_ADA,
				ARABIC_PREP_HASHA,
				ARABIC_LETTER_LAM+ARABIC_LETTER_YEH+ARABIC_LETTER_SEEN,)
		 
		
#Interogative
INTG = ()
#Negative
NEG = (
				ARABIC_LETTER_LAM+ARABIC_LETTER_MEEM,
				ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,)
		 
		
#Conditional
COND = (ARABIC_LETTER_LAM+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_MEEM+ARABIC_LETTER_NOON,
				ARABIC_LETTER_MEEM+ARABIC_LETTER_HEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_PREP_MATA,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_KAF+ARABIC_LETTER_YEH+ARABIC_LETTER_FEH,
				ARABIC_LETTER_HAH+ARABIC_LETTER_YEH+ARABIC_LETTER_THEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_THAL+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_THAL+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF,

				ARABIC_LETTER_ALEF+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF,
				ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_THAL+ARABIC_LETTER_ALEF,

				ARABIC_LETTER_ALEF+ARABIC_LETTER_THAL,
				ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW+ARABIC_LETTER_THAL,

				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_YEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,

				ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_YEH+ARABIC_LETTER_YEH+ARABIC_LETTER_NOON,

				ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_YEH,
				ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_YEH+ARABIC_LETTER_YEH
				)
		 
#Vocals particles		
VOC = (ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE,
				ARABIC_LETTER_YEH+ARABIC_LETTER_ALEF)
		
TENN = (ARABIC_LETTER_ALEF+ARABIC_LETTER_SEEN+ARABIC_LETTER_MEEM, 
		ARABIC_LETTER_ALEF+ARABIC_LETTER_SEEN+ARABIC_LETTER_TEH,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH_MARBUTA,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_BEH+ARABIC_LETTER_NOON+ARABIC_LETTER_MEEM,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_MEEM+ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_MEEM+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE+ARABIC_LETTER_TEH_MARBUTA,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_THEH+ARABIC_LETTER_NOON+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON+ARABIC_LETTER_TEH+ARABIC_LETTER_TEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF+ARABIC_LETTER_YEH+ARABIC_LETTER_MEEM+ARABIC_LETTER_NOON+" "+ARABIC_WORD_ALLAH)

		
DEM_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in DEM] 	
DEMLOC_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in DEM] 
REL_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in REL]
PPRON1_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PPRON1]
PPRON2_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PPRON2]
PPRON3_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PPRON3]
POSPRON_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in POSPRON]
PREP_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PREP]

#PSOLO_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PSOLO]
PVSOLO_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in PVSOLO]

CONJ_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CONJ]
ACC_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in ACC]
NEG_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in NEG]
COND_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in COND]
EXP_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in EXP]
VOC_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in VOC] 
TENN_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in TENN]
KANA_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in KANA]

	

#Noun-specific Prefixes
#CONJ+P+AL
PRFX_CONJPAL = (
				ARABIC_LETTER_WAW+ARABIC_LETTER_BEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				ARABIC_LETTER_WAW+ARABIC_LETTER_KAF+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				ARABIC_LETTER_WAW+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM,
				ARABIC_LETTER_FEH+ARABIC_LETTER_BEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				ARABIC_LETTER_FEH+ARABIC_LETTER_KAF+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				ARABIC_LETTER_FEH+ARABIC_LETTER_LAM+ARABIC_LETTER_LAM,)
#CONJ+AL
PRFX_CONJAL = (
				ARABIC_LETTER_WAW+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				ARABIC_LETTER_FEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
				)

#P+AL
PRFX_PAL = (ARABIC_LETTER_BEH+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
			ARABIC_LETTER_KAF+ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,
			ARABIC_LETTER_LAM+ARABIC_LETTER_LAM,)
#CONJ+P
PRFX_CONJP = (ARABIC_LETTER_WAW+ARABIC_LETTER_BEH,
				ARABIC_LETTER_WAW+ARABIC_LETTER_KAF,
				ARABIC_LETTER_WAW+ARABIC_LETTER_LAM,
				ARABIC_LETTER_WAW+ARABIC_LETTER_FEH,
				ARABIC_LETTER_FEH+ARABIC_LETTER_BEH,
				ARABIC_LETTER_FEH+ARABIC_LETTER_KAF,
				ARABIC_LETTER_FEH+ARABIC_LETTER_LAM,
				ARABIC_LETTER_FEH+ARABIC_LETTER_FEH,)
#AL
PRFX_AL = (ARABIC_LETTER_ALEF+ARABIC_LETTER_LAM,)
#CONJ	
PRFX_CONJ = (ARABIC_LETTER_WAW,ARABIC_LETTER_FEH,)
#P
PRFX_P = (ARABIC_LETTER_BEH,
		ARABIC_LETTER_KAF,
		ARABIC_LETTER_LAM,)



##Verb specific Prefix
#PV+SEEN+CONJ
PRFX_CONJSPV = (ARABIC_LETTER_WAW+ARABIC_LETTER_SEEN+ARABIC_LETTER_YEH,
		ARABIC_LETTER_WAW+ARABIC_LETTER_SEEN+ARABIC_LETTER_NOON,
		ARABIC_LETTER_WAW+ARABIC_LETTER_SEEN+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_WAW+ARABIC_LETTER_SEEN+ARABIC_LETTER_TEH,
		ARABIC_LETTER_FEH+ARABIC_LETTER_SEEN+ARABIC_LETTER_YEH,
		ARABIC_LETTER_FEH+ARABIC_LETTER_SEEN+ARABIC_LETTER_NOON,
		ARABIC_LETTER_FEH+ARABIC_LETTER_SEEN+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_FEH+ARABIC_LETTER_SEEN+ARABIC_LETTER_TEH)

#PV+CONJ
PRFX_CONJPV = (ARABIC_LETTER_WAW+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,
		ARABIC_LETTER_WAW+ARABIC_LETTER_TEH,
		ARABIC_LETTER_WAW+ARABIC_LETTER_NOON,
		ARABIC_LETTER_WAW+ARABIC_LETTER_YEH,
		ARABIC_LETTER_FEH+ARABIC_LETTER_ALEF,
		ARABIC_LETTER_FEH+ARABIC_LETTER_TEH,
		ARABIC_LETTER_FEH+ARABIC_LETTER_NOON,
		ARABIC_LETTER_FEH+ARABIC_LETTER_YEH,)
#PV+SEEN
PRFX_SEENPV = (ARABIC_LETTER_SEEN+ARABIC_LETTER_NOON,
		ARABIC_LETTER_SEEN+ARABIC_LETTER_YEH,
		ARABIC_LETTER_SEEN+ARABIC_LETTER_TEH,
		ARABIC_LETTER_SEEN+ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,)

#SEEN
PRFX_SEEN = (ARABIC_LETTER_SEEN,)

#PV
PRFX_PV = (ARABIC_LETTER_TEH,
		ARABIC_LETTER_YEH,
		ARABIC_LETTER_NOON,
		ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE,)
#SAWFA
PRFX_SAWFA = (ARABIC_LETTER_SEEN+ARABIC_LETTER_WAW+ARABIC_LETTER_FEH,)

#------------Prefixes Regex----------------------
###Noun-Specific###
CONJPAL_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJPAL]

CONJAL_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJAL]
AL_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_AL]
CONJP_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJP]
PAL_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_PAL]
CONJ_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJ]
P_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_P]
###Verb-Specific###
CONJSPV_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJSPV]
CONJPV_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_CONJPV]
SEENPV_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_SEENPV]
PV_REGX =  [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_PV]
SEEN_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_SEEN]

SAWFA_REGX = [(len(prefix), re.compile(u"%s" % prefix, re.UNICODE)) for prefix in PRFX_SAWFA]

#------------Suffixes Regex--------------------------
###Possessives Pronouns###
POSPRON1_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in POSPRON1]	
POSPRON2_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in POSPRON2] 
POSPRON3_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in POSPRON3]

###Case Ending###
CE_SF_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CE_SF] 	
CE_DM_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CE_DM] 	
CE_DF_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CE_DF] 	
CE_PM_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CE_PM] 	
CE_PF_REGX = [(len(p), re.compile(u"%s" % p, re.UNICODE)) for p in CE_PF] 	

